name: Publish icons-react package to NPM

on:
  # push:
  #   tags:
  #     - 'v*'
  #   paths-ignore:
  #     - 'README.md'

  # workflow_dispatch:

  workflow_run:
    workflows: [Publish icons-svg package to NPM]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          scope: '@d-matrix'
      - name: Check folders and files
        run: pwd
      - run: tree -L 3
      - run: cat .npmrc

      - name: Change directory
        run: cd packages/icons-react

      - name: Install dependencies
        run: npm install

      - name: Publish
        run: npm run publish --workspace-root
        env:
          NPM_AUTHTOKEN: ${{ secrets.NPM_AUTHTOKEN }}
